### ISSUE TITLE
"View supported devices" link on https://dahliaos.io/#features is broken

### ISSUE THREAD

**Issue by aleyan** [dahliaOS/website#30]
"View supported devices" link on https://dahliaos.io/#features leads to `https://github.com/dahliaOS/documentation/blob/main/supported-hardware.md` which is a 404. I think it should lead to `https://github.com/dahliaOS/documentation/blob/main/docs/articles/hardware/supported-devices.md`. I looked at changing it myself, but in the source in this repo, I only saw links to `https://dahliaos.io/docs/#/articles/hardware/supported-devices`, so I wasn't sure if it is the right place.

https://github.com/dahliaOS/website/blob/3a395bae563cabd590c56f87e7a25e8839808479/views/index.ejs#L170

**Comment by nmcain** [comment]
I'm so sorry for that! We are undergoing a transition to a new web host,
the website is running a very old copy from november. I'll update it on the
host's end to fix that. Thanks!

**Comment by hexa-one** [comment]
You may want to read my personal testing repo for now. https://hexa-one.github.io/documentation/docs/#/articles/hardware/supported-devices

Sorry for the inconvenience!

**Comment by aleyan** [comment]
Thank you so much for quick turnaround!
