### ISSUE TITLE
Download button non-functional on mobile

### ISSUE THREAD

**Issue by winksaville** [dahliaOS/website#34]
**Describe the bug**
On an Android and a iPhone when pressing DOWNLOAD button
on the main page nothing happens. But it does work on my
Desktop computer using Chrome and if I enable "Desktop site" on
my Android phone it also works as expected. So this is mobile
specific.

**What kind of a bug is it?**
User interface on the site is not working as expected.

**To Reproduce**
0. On a mobile device
1. Go to https://dahliaos.io
2. Press Download, no animation
3. Release DOWNLOAD, nothing happens

**Expected behavior**
Because DOWNLOAD is a button it should animate when pressed and when
released it should "goto" the linked page or section. The "LEARN MORE"
button directly above it does animate and on release renders the expected
information. The DOWNLOAD button does nothing.

**Screenshots**
N/A

**Browser (please complete the following information):**
 - Desktop: Chrome
 - Mobile: Chrome (on Android), Safari (on iPhone)

**Additional context**
N/A

**Comment by SincerelyFaust** [comment]
Works for me on Android, also Chrome.

**Comment by winksaville** [comment]
Doesn't work for me on my Android using Chrome nor on my wifes iPhone using Safari.

**Comment by winksaville** [comment]
@SincerelyFaust, I'd like to "test" PR #35, could you or some one else comment on issue #33 with some information on how to build/test the website locally? If it's possible I'd be happy to provide a PR for that issue too.

**Comment by nmcain** [comment]
@Looskie On mobile devices of a certain width, it appears that the download button gets placed beneath text, making it non-functional.
![image](https://user-images.githubusercontent.com/18690588/121061667-fe37ba00-c778-11eb-88c2-c911e49d6960.png)

**Comment by Looskie** [comment]
I see that, will fix

Thanks!

**Comment by winksaville** [comment]
@nmcain, @Looskie; some additional info.

On my Android in portait orientation it FAILS:

![screenshot-dahliaos-download-portrait-fails](https://user-images.githubusercontent.com/1024284/121064616-ac912e80-c77c-11eb-8b5f-ca8a68ddc707.png)

But in landscape orientation it's OK:

![screenshot-dahialos-download-landscape-ok](https://user-images.githubusercontent.com/1024284/121064772-d64a5580-c77c-11eb-8e59-dd4afafa670f.png)

Same for my wifes iPhone, OK in landscape FAILS in portrait.

**Comment by Looskie** [comment]
Ill be pushing an update later today!

**Comment by winksaville** [comment]
> Ill be pushing an update later today!

A quick local test of the current master on my desktop and this bug seems to be fixed. I went into developer mode on chrome and was able to create a narrow window and the DOWNLOAD button can be forced into the "News" and the button does work where as on the release version it didn't. Of course YMMV, but if your testing also indicates this bug is fixed it would be nice to release a new version of the website.

**Comment by Looskie** [comment]
This will be fixed with the NextJS rewrite coming in a week or two. will link when I create the PR

**Comment by horberlan** [comment]
i'll fix it! I will request a pull request soon...

**Comment by horberlan** [comment]
i'll fix it! I will suggest a pull request soon...

**Comment by Looskie** [comment]
> i'll fix it! I will suggest a pull request soon...

We already have an open PR that fixes this, also, you're probably going to hate working with it LOL, its sooo poorly coded, this rewrite fixes everything

**Comment by horberlan** [comment]
> > i'll fix it! I will suggest a pull request soon...
> 
> We already have an open PR that fixes this, also, you're probably going to hate working with it LOL, its sooo poorly coded, this rewrite fixes everything 

alright, leave the front-end with me
