### ISSUE TITLE
[BUG] MUI overwriting the font family

### ISSUE THREAD

**Issue by SincerelyFaust** [dahliaOS/website#84]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The font that has been set globally for the website is Inter but it seems to not be displayed properly in the drawer, looks like some other font is being used.

### Expected behavior

it should be using Inter as the font.

### Steps to reproduce

1. Open the drawer
2. Take a look

### Environment (remove values that do not apply)

```markdown
- OS: macOS and iOS
- Browser: Google Chrome and Safari
```

### Anything else?

![image](https://user-images.githubusercontent.com/44751736/202916607-4e62bfc0-268a-4c2e-adf5-11b9702477cc.png)
and compare it to this
![image](https://user-images.githubusercontent.com/44751736/202916614-3288bb1e-cbec-4b9c-b31a-355f8702d537.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SincerelyFaust** [comment]
Same goes for the modal in the download card.
![image](https://user-images.githubusercontent.com/44751736/203134244-fb58a6e6-8b7b-4157-8722-309011cb7652.png)

**Comment by SincerelyFaust** [comment]
MUI seems to be overwriting the typography, perhaps setting Inter as the main font in the createMUITheme class would fix this?

**Comment by Looskie** [comment]
seems to be fixed @SincerelyFaust , reopen if anything else you see pops up
